name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: gyamada22

          # Ativa apenas o essencial
          base: header, activity

          # Deixa o activity bem limpo
          base_indepth: false
          plugin_activity: yes
          plugin_activity_limit: 0
          plugin_activity_days: 365
          plugin_activity_filter: all

          # Desliga todo o resto
          plugin_languages: no
          plugin_isocalendar: no
          plugin_lines: no
          plugin_stars: no
          plugin_traffic: no
          plugin_followup: no
